fix: store favorites regardless of languages
CorentinTh/it-tools pull request #1202
Opened 2024-07-12 20:27 UTC by sharevb

Fix #1110

2024-08-07 07:28 UTC, CorentinTh requested changes
Maybe no need for continuing to use the `name` along the path ?

2024-08-07 07:28 UTC, CorentinTh commented on src/tools/tools.store.ts
> +      favoriteToolsName.value = favoriteToolsName.value.filter(name => get(tool).name !== name && get(tool).path !== name);
```suggestion
      favoriteToolsName.value = favoriteToolsName.value.filter(name => get(tool).path !== name);
```

2024-08-07 07:28 UTC, CorentinTh commented on src/tools/tools.store.ts
> +        || favoriteToolsName.value.includes(get(tool).path);
```suggestion
      return favoriteToolsName.value.includes(get(tool).path);
```

2024-08-07 07:28 UTC, CorentinTh commented on src/tools/tools.store.ts
> +      .map(favoriteName => tools.value.find(({ name, path }) => name === favoriteName || path === favoriteName))
```suggestion
      .map(favoritePath => tools.value.find(({ path }) => path === favoritePath))
```

2024-08-07 07:28 UTC, CorentinTh commented on src/tools/tools.store.ts
>      return favoriteToolsName.value
```suggestion
    return favoriteToolsPaths.value
```

2024-08-07 07:47 UTC, sharevb commented
> Maybe no need for continuing to use the `name` along the path ?

I used both in order that current favorites are not loss by this change. Else, I think all favorites will be lost for everyone, no ?

2024-10-22 08:21 UTC, CorentinTh approved these changes

2024-10-22 08:21 UTC, merged