JWT parser
CorentinTh/it-tools pull request #262
Opened 2022-11-19 10:40 UTC by bastantoine

### Description

This PR adds a new tool that parses a JWT (*JSON Web Token*) and display its values in a human-readable way.

This tools also display enhanced informations about the claims and values based on some standard well defined fields when possible.

### Additional context

*Note*: this doesn't check the validity of the signature of the JWT. I can add that if you feel that it can be useful, but I'd rather get this first part approved, or not, first.

---

### What is the purpose of this pull request? 

- [ ] Bug fix
- [x] New Feature
- [ ] Documentation update
- [ ] Other

### Before submitting the PR, please make sure you do the following

- [x] Submit the PR against the `dev` branch.
- [x] Check that there isn't already a PR that solves the problem the same way to avoid creating a duplicate.

2022-12-02 08:18 UTC, bastantoine commented
Any news @CorentinTh ?

2022-12-20 07:24 UTC, bastantoine commented
Ping @CorentinTh 😄

2022-12-20 18:20 UTC, CorentinTh commented
Hello @bastantoine !
First of all, I'm trully sorry to have taken so long to take the time to review your pr 🙏🏻 

Thank you to have taken the time to contribute, a JWT parser will be a fine adition to the it-tool collection, I'm looking forward to your future contributions ❤️

2022-12-20 18:22 UTC, CorentinTh requested changes
Just a few thing before the merge :

* Use camelCase for variables and functions name 
* Always show the complete values (remove the *Display parsed value?* toggle) -> it had nothing to hide some information here
* Please rebase your pr with dev to remove the conflicts

2022-12-20 18:22 UTC, CorentinTh commented on src/tools/jwt-parser/jwt-parser.service.ts
> +    return { header: header, payload: payload };
```suggestion
    return { header, payload };
```

2022-12-20 18:24 UTC, CorentinTh commented
Also, this project uses [pnpm](https://pnpm.io/) instead of npm, so can you remove the package-lock.json and reinstall using pnpm please 🙏🏻

2022-12-27 08:37 UTC, CorentinTh commented
Thanks for those update !

2022-12-27 08:37 UTC, CorentinTh approved these changes

2022-12-27 08:38 UTC, merged

2022-12-27 08:39 UTC, CorentinTh commented
I'll try to put the dev branch to prodution this week 💪🏻

2022-12-28 21:14 UTC, bastantoine commented
Great thanks! Joyeuses fêtes 🎉 !