feat(new-tool): json minify
CorentinTh/it-tools pull request #265
Opened 2023-02-02 11:35 UTC by tsonglew

add new tool:  json minify

2023-02-03 09:55 UTC, CorentinTh requested changes
Hi @tsonglew !

Thank you for submiting this new tool, that's a great idea!
Before merging, can you please fix the linting issues, to match the rest of the app 🙏🏻 

Thanks again for your time 💪🏻

2023-02-03 09:55 UTC, CorentinTh commented on src/tools/json-minify/index.ts
> +  description: 'Minify your JSON to a string',
```suggestion
  description: 'Minify and compress your JSON by removing unnecessary withe spaces.',
```

2023-02-04 08:38 UTC, tsonglew commented
PTAL @CorentinTh

2023-02-04 08:56 UTC, CorentinTh approved these changes
👌🏻

2023-02-04 08:56 UTC, merged

2023-02-04 08:56 UTC, CorentinTh commented
Thank you for taking the time to submit a PR 🙏🏻

2023-02-04 09:01 UTC, CorentinTh commented
It's live : https://it-tools.tech/json-minify

2023-02-06 02:52 UTC, tsonglew commented
Thx !🎉🎉🎉