fix(roman-numeral-converter):  checks for valid input and conversion …
CorentinTh/it-tools pull request #332
Opened 2023-04-06 11:56 UTC by cgoIT

…enhancements

Validates if numeral values are between 1 and 3999999. Validates if a roman number is valid.

Fixes #274

2023-04-06 12:01 UTC, cgoIT commented
On thing I just recognized is, that the copy button doesn't make to much sense if the numeral value is greater than 3999. Maybe it would be an option to disable the copy button if the number is greater than 3999?

2023-04-07 17:50 UTC, CorentinTh requested changes
Thank you for this PR, and sorry for taking so long to review it 

I think we can stick to roman number below 3999
I'm not trully fan of the span with overline, it's not inputable and nor copyable and force to use v-html which I dont really want in the app

2023-04-07 17:50 UTC, CorentinTh commented on src/tools/roman-numeral-converter/roman-numeral-converter.vue
> +          <span v-html="outputRoman"></span>
I'm not a fan of v-html, it can lead to a huge security flaw, and is often synonyme of bad design

2023-04-07 17:50 UTC, CorentinTh commented on src/tools/roman-numeral-converter/roman-numeral-converter.vue
> +}
use a computed instead

2023-04-08 17:33 UTC, CorentinTh approved these changes
Looks great, thanks 🙏🏻

2023-04-08 17:33 UTC, merged