YAML Validate and Format
CorentinTh/it-tools pull request #779
Opened 2023-11-27 21:53 UTC by isaiah-j

Added a tool that validates/formats YAML

https://github.com/CorentinTh/it-tools/assets/66272034/2c6d2330-3a76-436d-b955-4f296bf2b231

2023-11-29 13:10 UTC, CorentinTh requested changes
Great tool, thank you for the PR ans the video :pray: 
Just few changes and we are good to merge :muscle: 

We currently have the [`yaml`](https://www.npmjs.com/package/yaml) package installed in it-tools and you PR add [`js-yaml`](https://www.npmjs.com/package/js-yaml) (which as not been updated since 3 years)

2023-11-29 13:10 UTC, CorentinTh commented on src/tools/yaml-viewer/index.ts
> +  redirectFrom: ['/yaml-viewer'],
Redirection is used for legacy routing support 
+ add the creation date 
```suggestion
  createdAt: new Date('2023-11-29'),
```

2023-11-29 13:10 UTC, CorentinTh commented on src/tools/yaml-viewer/yaml-models.ts
> +import yaml from 'js-yaml';
Maybe use the already installed `yaml` package ?

2024-01-30 20:06 UTC, jcgoette commented
What is missing to get this across this finish line?

2024-01-31 09:54 UTC, CorentinTh submitted a review, later dismissed
Hi!
Thank you for this PR :pray: 
And very sorry this very late approval :pleading_face:

2024-01-31 09:54 UTC, CorentinTh commented on src/tools/yaml-viewer/index.ts
> +  createdAt: new Date('2023-11-29'),
```suggestion
  createdAt: new Date('2024-01-31'),
```

2024-01-31 09:58 UTC, merged