The entire website is i18nized
CorentinTh/it-tools pull request #894
Opened 2024-02-22 10:02 UTC by Amery2010

feat(i18n): The entire website is i18nized, and zh-CN translation is added, can be more easily translated into other multi-language versions

2024-03-11 10:23 UTC, CorentinTh requested changes
Please no global tracking script

2024-03-11 10:46 UTC, Amery2010 commented on index.html
> +    </script>
Sorry, I submitted the website statistics code for my own use by mistake. I will correct it.

2024-09-10 09:02 UTC, steffenrapp commented
@Amery2010 are you still working on this PR? I started a similar one with #1178 and just realized yours.

2024-09-16 04:14 UTC, Amery2010 commented
> @Amery2010 are you still working on this PR? I started a similar one with #1178 and just realized yours.

I completed the translation of the previous version of the site a few months ago, but I only did the translation work in Chinese, French and other languages. Later, I stopped the translation work due to other projects.

You can translate it again, or expand the translation based on my project.

2024-10-20 11:24 UTC, closed without merging